-- V2: core domain schema (SPEC §3). JPA runs with ddl-auto=validate, so these tables must
-- match the entity mappings exactly. PostgreSQL dialect.

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,
    oauth_provider      VARCHAR(20)  NOT NULL,
    oauth_id            VARCHAR(100) NOT NULL,
    email               VARCHAR(100) NOT NULL,
    nickname            VARCHAR(30)  NOT NULL,
    avatar_type         VARCHAR(20)  NOT NULL,
    total_study_minutes BIGINT       NOT NULL,
    current_streak      INTEGER      NOT NULL,
    longest_streak      INTEGER      NOT NULL,
    last_study_date     DATE,
    CONSTRAINT uq_users_provider_oauth_id UNIQUE (oauth_provider, oauth_id)
);

CREATE TABLE rooms (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP   NOT NULL,
    updated_at           TIMESTAMP   NOT NULL,
    name                 VARCHAR(50) NOT NULL,
    host_user_id         BIGINT      NOT NULL,
    capacity             INTEGER     NOT NULL,
    status               VARCHAR(20) NOT NULL,
    invite_code          VARCHAR(12) NOT NULL,
    current_member_count INTEGER     NOT NULL,
    version              BIGINT      NOT NULL,
    CONSTRAINT uq_rooms_invite_code UNIQUE (invite_code)
);

CREATE TABLE room_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    room_id   BIGINT      NOT NULL,
    user_id   BIGINT      NOT NULL,
    role      VARCHAR(20) NOT NULL,
    presence  VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_room_members_room_user UNIQUE (room_id, user_id)
);

CREATE TABLE tomolog_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP   NOT NULL,
    updated_at      TIMESTAMP   NOT NULL,
    room_id         BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    cycle_number    INTEGER     NOT NULL,
    emoji           VARCHAR(8)  NOT NULL,
    memo            VARCHAR(100),
    studied_minutes INTEGER     NOT NULL
);

CREATE TABLE room_pets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    room_id       BIGINT    NOT NULL,
    growth_points INTEGER   NOT NULL,
    level         INTEGER   NOT NULL,
    CONSTRAINT uq_room_pets_room_id UNIQUE (room_id)
);

CREATE TABLE badges (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    user_id   BIGINT      NOT NULL,
    type      VARCHAR(30) NOT NULL,
    earned_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_badges_user_type UNIQUE (user_id, type)
);

CREATE INDEX idx_room_members_room_id ON room_members (room_id);
CREATE INDEX idx_tomolog_entries_room_id ON tomolog_entries (room_id);
CREATE INDEX idx_badges_user_id ON badges (user_id);
